# Generated by Django 3.1.2 on 2020-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(blank=True, choices=[('postgres', 'PostgreSQL'), ('sqlite', 'SQLite')], help_text='The Type of the Database being connected to.', max_length=20, verbose_name='Database Type')),
                ('user', models.CharField(blank=True, help_text='The username of the account being used to connect to a database.', max_length=225, verbose_name='Database Account Username')),
                ('password', models.CharField(blank=True, help_text='The password of the account being used to connect to a database.', max_length=225, verbose_name='Database Account Password')),
                ('host', models.CharField(blank=True, help_text='The host of the database being connected to.', max_length=50, verbose_name='Database Host')),
                ('port', models.CharField(blank=True, help_text='The port number of the database being connected to.', max_length=5, verbose_name='Database Port')),
                ('db_name', models.CharField(blank=True, help_text='The name of the specific database being connected to.', max_length=225, verbose_name='Database Name')),
            ],
        ),
    ]
